// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Name  string `json:"name"`
	StuNo string `json:"stu_no"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	StuNo string `json:"stu_no"`
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type UpdateRequest struct {
	Id    int64  `json:"id"`
	Name  string `json:"name,optional"`
	StuNo string `json:"stu_no"`
}

type UpdateResponse struct {
}
